### ISSUE TITLE
Disponibilités de la semaine

### ISSUE THREAD

**Issue by ialgrin** [publicarchitectura/cbc#10]
Bonsoir,
pourriez-vous mentionner ici vos disponibilités pour la semaine afin d'éventuellement planifier un moment de travail commun pour le projet du Conseil des Bâtiments Civils ?
Merci
Isabelle

**Comment by ialgrin** [comment]
Mes disponibilités : mercredi et jeudi matin jusqu'à 13h30.

**Comment by emchateau** [comment]
Chère Isabelle,
Je suis cette semaine malheureusement vraiment à la course.
Serait-il possible de se voir lundi matin ou mardi matin ?
Salutations, 
Emmanuel

**Comment by ialgrin** [comment]
Bonjour, 
Pour ma part je peux travailler chez moi sans problème cette semaine.
La semaine prochaine je serai à Québec pour la semaine du numérique, je ne serai donc pas disponible.
Toutefois, je crois que @vmichaud04  avait besoin de vous rencontrer pour avancer sur la bibliographie.
En vous souhaitant une bonne semaine,
Isabelle
