### ISSUE TITLE
Produire les manifestes pour les images

### ISSUE THREAD

**Issue by emchateau** [publicarchitectura/cbc#20]
En prévision de l’utilisation de IIIF et de Nakala, créer un manifest pour accéder aux images.
- [API Présentation de IIIF](https://iiif.io/api/presentation/3.0/#52-manifest)
- [Manifest editor](https://digital.bodleian.ox.ac.uk/manifest-editor/)
- [Documentation de IIIF sur Gallica](https://api.bnf.fr/fr/api-iiif-de-recuperation-des-images-de-gallica)

**Comment by lenaMK** [comment]
Je suis dans la doc iiif depuis hier mais il doit y avoir quelque chose que je n'ai pas compris du tout. Est-ce qu'on peut s'en parler? 
@emchateau

**Comment by emchateau** [comment]
Salut Lena,
J’écoute Johanna Drucker, je pense que je serai sorti vers 13h.
Salutations,

Emmanuel Château-Dutier

**Comment by lenaMK** [comment]
Documentation utile: 
- bodleian manifest editor: https://iiif.github.io/training/intro-to-iiif/IIIF_MANIFESTS.html
- exemple de manifestes: https://github.com/biblissima/iiif-manifests-demo

Structure (nested):
manifeste + metadonnées sur le manifeste (id, description, attribution, logo, thumbnail, metadata, related) > Sequences > Canvases

Chaque Canvas (page) a des informations (id, type, label, hauteur, largeur) et un array d'images (au moins une pour ne pas qu'elle soit vide. En contient plusieurs dans le cas de reconstitutions de manuscrits par exemples).
Chaque image contient des ressources (iiif image) et des services.


Question:
- Comment générer les IDs dans le manifeste? @emchateau

**Comment by lenaMK** [comment]
https://api.nakala.fr/doc

Exemple: [Petit Larousse illustré, édition 1915-114, page 1066 ](https://www.nakala.fr/11280/bb0bd067)
DOI : https://doi.org/11280/bb0bd067
identifier: 10.34847/nkl.dcbar7u5
fileIdentifier: 2173fa62f03ec375f581e4315e0091b215d31f3a

![image](https://user-images.githubusercontent.com/14301102/121382741-e6953880-c914-11eb-869c-4005817eeef0.png)


requête pour avoir les informations sur l'image: 
- Structure: /iiif/{identifier}/{fileIdentifier}/info.json
- URL: https://api.nakala.fr/iiif/10.34847%2Fnkl.dcbar7u5/2173fa62f03ec375f581e4315e0091b215d31f3a/info.json
- Curl: curl -X GET "https://api.nakala.fr/iiif/10.34847%2Fnkl.dcbar7u5/2173fa62f03ec375f581e4315e0091b215d31f3a/info.json" -H  "accept: application/json"


requête pour l'image: 
- Structure: /iiif/{identifier}/{fileIdentifier}/{region}/{size}/{rotation}/{quality}.{format}
- URL: https://api.nakala.fr/iiif/10.34847%2Fnkl.dcbar7u5/2173fa62f03ec375f581e4315e0091b215d31f3a/full/1000%2C/0/default.jpg
- curl -X GET "https://api.nakala.fr/iiif/10.34847%2Fnkl.dcbar7u5/2173fa62f03ec375f581e4315e0091b215d31f3a/full/1000%2C/0/default.jpg" -H  "accept: application/json"

**Comment by lenaMK** [comment]
faire la base du manifeste et tester avec 3 images
recevoir liens des images test uploadées sur Nakala @emchateau

**Comment by lenaMK** [comment]
écrire les étapes pour le script qui produira le manifeste pour l'ensemble des PVs
dans repo https://github.com/publicarchi/cbc/blob/master/testManifeste/Script-manifeste.md
