### ISSUE TITLE
Faire une revue de bibliographie sur l’utilisation de la textométrie en histoire

### ISSUE THREAD

**Issue by emchateau** [publicarchitectura/cbc#7]
- [x] Identifier les termes
- [x] Lister les ressource à interroger
- [x] Rassembler la bibliographie
- [ ] Réviser et organiser la bibliographie

**Comment by emchateau** [comment]
J'ai commencé à penser aux catégories que vous pourriez établir pour commencer

## Méthodes de fouille de texte et la textométrie
## Étude discours et des actes de langage
## Linguistique de corpus
## Lexicométrie, textométrie, logométrie et sciences historiques

@vmichaud04

**Comment by vmichaud04** [comment]
@emchateau 

Bonjour monsieur Château. Merci pour ces catégories. Elles seront en effet très utiles pour les textes que j'ai déjà trouvé. Par contre je me demandais si vous pourriez me préciser la différence que vous entendez entre les catégories _Étude discours et des actes de langage_ et _Linguistique de corpus_. J'envisageais de mettre les texte plus théoriques sur l'analyse de texte et la linguistique dans la première et les études de cas/mises en application dans l'autre. Est-ce ce à quoi vous pensiez? 

Merci

**Comment by emchateau** [comment]
Je pensais à la linguistique de corpus, au sens de François Rastier
L’étude du discours ou des actes de langage s’en distingue par la focalisation sur la dimension rhétorique du texte et l’étude de l’argumentation.
