### ISSUE TITLE
Mettre à disposition la transcription réalisée le 20 mars

### ISSUE THREAD

**Issue by ialgrin** [publicarchitectura/cbc#9]
Fournir l'accès à la transcription réalisée en binôme lundi 20 mars avec le schéma XML-TEI pour débuter les échantillons de transcriptions.

**Comment by emchateau** [comment]
Chère Isabelle,

J'ai poussé les documents sur lesquels nous avions travaillé.
Si vous clonez le dépôt git, vous aurez le document XML et le schéma.

Le document sur lequel nous avons travaillé ensemble la dernière fois dans F21 2534 est nommé https://github.com/publicarchitectura/cbc/blob/pvF21-2534.xml

La transcription de F21 2540 se trouve dans https://github.com/publicarchitectura/cbc/blob/master/notes.tei.xml

Bien cordialement,
Emmanuel

**Comment by ialgrin** [comment]
Bonjour, 

C'est fabuleux, merci beaucoup !
Bien cordialement, 

Isabelle

**Comment by emchateau** [comment]
Salut Isabelle,
N’oubliez pas de fermer les issues quand les choses sont réglées.
Salutations,
Emmanuel
